# Generated by Django 4.0.6 on 2022-07-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafetriatype',
            name='cafeteria',
            field=models.CharField(choices=[('cafe 1', 'Anchor Cafteria 1'), ('Cafe 2', 'Anchor Cafeteria 2')], max_length=20),
        ),
    ]
